jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UseNode@1
        inputs:
          version: '12.x'
        displayName: 'Use Node 12.x'
      - script: |
          npm ci
        displayName: 'Install dependencies'
      - script: |
          npm run build --if-present
        displayName: "Run build"
      - script: |
          npm test -- -c=ci
        displayName: 'Run test'
      - script: |
          npm run lint --if-present
        displayName: 'Run linting'
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'dist'
          targetPath: 'dist'
        displayName: 'Publish build artifacts'
      - task: PublishTestResults@2
        inputs:
          testRunTitle: zawgyi-unicode-converter
          searchFolder: $(System.DefaultWorkingDirectory)/dist/junit
          testResultsFormat: JUnit
          testResultsFiles: "**/TESTS*.xml"
        condition: succeededOrFailed()
        displayName: Publish test results
