jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UseNode@1
        inputs:
          version: '14.x'
        displayName: 'Use Node 14.x'
      - script: |
          npm ci
        displayName: 'Install dependencies'
      - script: |
          npm run lint --if-present
        displayName: 'Run linting'
      - script: |
          npm run build
        displayName: "Run build"
      - script: |
          npm test --if-present
        displayName: 'Run test'
      - task: PublishPipelineArtifact@1
        inputs:
          artifactName: 'dist'
          targetPath: 'dist'
        displayName: 'Publish build artifacts'
      - task: PublishTestResults@2
        inputs:
          testRunTitle: JUnit
          searchFolder: $(System.DefaultWorkingDirectory)/junit
          testResultsFormat: JUnit
          testResultsFiles: "**/TESTS*.xml"
        condition: succeededOrFailed()
        displayName: Publish test results
